const collection = [
  // Cards of Spade
  { key: '2S', value: 2, type: 'spade', title: '2-spade' },
  { key: '3S', value: 3, type: 'spade', title: '3-spade' },
  { key: '4S', value: 4, type: 'spade', title: '4-spade' },
  { key: '5S', value: 5, type: 'spade', title: '5-spade' },
  { key: '6S', value: 6, type: 'spade', title: '6-spade' },
  { key: '7S', value: 7, type: 'spade', title: '7-spade' },
  { key: '8S', value: 8, type: 'spade', title: '8-spade' },
  { key: '9S', value: 9, type: 'spade', title: '9-spade' },
  { key: '10S', value: 11, type: 'spade', title: '10-spade' },
  { key: 'JS', value: 12, type: 'spade', title: 'jack-spade' },
  { key: 'QS', value: 13, type: 'spade', title: 'queen-spade' },
  { key: 'KS', value: 14, type: 'spade', title: 'king-spade' },
  { key: 'AS', value: 15, type: 'spade', title: 'a-spade' },
  // Cards of Club
  { key: '2C', value: 2, type: 'club', title: '2-club' },
  { key: '3C', value: 3, type: 'club', title: '3-club' },
  { key: '4C', value: 4, type: 'club', title: '4-club' },
  { key: '5C', value: 5, type: 'club', title: '5-club' },
  { key: '6C', value: 6, type: 'club', title: '6-club' },
  { key: '7C', value: 7, type: 'club', title: '7-club' },
  { key: '8C', value: 8, type: 'club', title: '8-club' },
  { key: '9C', value: 9, type: 'club', title: '9-club' },
  { key: '10C', value: 11, type: 'club', title: '10-club' },
  { key: 'JC', value: 12, type: 'club', title: 'jack-club' },
  { key: 'QC', value: 13, type: 'club', title: 'queen-club' },
  { key: 'KC', value: 14, type: 'club', title: 'king-club' },
  { key: 'AC', value: 15, type: 'club', title: 'a-club' },
  // Cards of Heart
  { key: '2H', value: 2, type: 'heart', title: '2-heart' },
  { key: '3H', value: 3, type: 'heart', title: '3-heart' },
  { key: '4H', value: 4, type: 'heart', title: '4-heart' },
  { key: '5H', value: 5, type: 'heart', title: '5-heart' },
  { key: '6H', value: 6, type: 'heart', title: '6-heart' },
  { key: '7H', value: 7, type: 'heart', title: '7-heart' },
  { key: '8H', value: 8, type: 'heart', title: '8-heart' },
  { key: '9H', value: 9, type: 'heart', title: '9-heart' },
  { key: '10H', value: 11, type: 'heart', title: '10-heart' },
  { key: 'JH', value: 12, type: 'heart', title: 'jack-heart' },
  { key: 'QH', value: 13, type: 'heart', title: 'queen-heart' },
  { key: 'KH', value: 14, type: 'heart', title: 'king-heart' },
  { key: 'AH', value: 15, type: 'heart', title: 'a-heart' },
  // Cards of Diamond
  { key: '2D', value: 2, type: 'diamond', title: '2-diamond' },
  { key: '3D', value: 3, type: 'diamond', title: '3-diamond' },
  { key: '4D', value: 4, type: 'diamond', title: '4-diamond' },
  { key: '5D', value: 5, type: 'diamond', title: '5-diamond' },
  { key: '6D', value: 6, type: 'diamond', title: '6-diamond' },
  { key: '7D', value: 7, type: 'diamond', title: '7-diamond' },
  { key: '8D', value: 8, type: 'diamond', title: '8-diamond' },
  { key: '9D', value: 9, type: 'diamond', title: '9-diamond' },
  { key: '10D', value: 11, type: 'diamond', title: '10-diamond' },
  { key: 'JD', value: 12, type: 'diamond', title: 'jack-diamond' },
  { key: 'QD', value: 13, type: 'diamond', title: 'queen-diamond' },
  { key: 'KD', value: 14, type: 'diamond', title: 'king-diamond' },
  { key: 'AD', value: 15, type: 'diamond', title: 'a-diamond' },
]

export default collection
